plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.3.0.cjs

packageExtensions:
  "@neos-project/neos-ui-extensibility@*":
    dependencies:
      "cross-spawn": "*"
