Neos:
  Neos:
    Ui:
      resources:
        stylesheets:
          Shel.Neos:ColorPickerEditor:
            resource: resource://Shel.Neos.ColorPicker/Public/ColorPickerEditor/Plugin.css
        javascript:
          Shel.Neos:ColorPickerEditor:
            resource: resource://Shel.Neos.ColorPicker/Public/ColorPickerEditor/Plugin.js

      frontendConfiguration:
        'Shel.Neos:ColorPickerEditor':
          # `mode` can be one of "rgba", "hsla", "hex"
          mode: 'rgba'
          # Colors which are available for quick selection
          presetColors: ['#D0021B', '#F5A623', '#F8E71C', '#8B572A', '#7ED321', '#417505', '#BD10E0', '#9013FE', '#4A90E2', '#50E3C2', '#B8E986', '#000000', '#4A4A4A', '#9B9B9B', '#FFFFFF']
