Neos:
  Neos:
    Ui:
      resources:
        stylesheets:
          Shel.Neos:ColorPickerEditor:
            resource: resource://Shel.Neos.ColorPicker/Public/ColorPickerEditor/Plugin.css
        javascript:
          Shel.Neos:ColorPickerEditor:
            resource: resource://Shel.Neos.ColorPicker/Public/ColorPickerEditor/Plugin.js

      frontendConfiguration:
        'Shel.Neos:ColorPickerEditor':
          # `mode` can be one of "rgba", "hsla", "hex"
          mode: 'rgba'
          # Show saturation/hue/alpha
          picker: false
          # Show hex/rgba fields
          fields: false
          # Colors which are available for quick selection
          presetColors: []
          # Hides the reset button if set to false
          allowEmpty: false
